<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<EnablePreviewFeatures>true</EnablePreviewFeatures>
		<NoWarn>$(NoWarn);CA1812;OPENAI001;MEAI001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.1.1" />
	  <PackageReference Include="ModelContextProtocol" Version="1.0.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
		<PackageReference Include="Azure.AI.Agents.Persistent" Version="1.0.0" />
		
    <PackageReference Include="Microsoft.Agents.AI" Version="1.0.0-preview.260212.1" />
		<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-preview.260212.1" />
	  <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.0.0-preview.260212.1" />
		<PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
		
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
	  <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.5" />
	  <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.5" />
	</ItemGroup>


	<ItemGroup>
		<Content Include="instructions/**" CopyToOutputDirectory="PreserveNewest" />
		<Content Include=".env" CopyToOutputDirectory="PreserveNewest" Condition="Exists('.env')" />
	</ItemGroup>
</Project>
